version: '3.8'

services:
  memoora-calls:
    build: .
    ports:
      - "5005:5005"
    environment:
      - NODE_ENV=development
      - PORT=5005
    env_file:
      - .env.local
    volumes:
      - ./audio:/app/audio
      - ./recordings:/app/recordings
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5005/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for enhanced state management (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

volumes:
  # redis_data:
