version: '3.8'

services:
  memoora:
    build: .
    ports:
      - "5005:5005"
    environment:
      - NODE_ENV=production
      - PORT=5005
      - BASE_URL=${BASE_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - MY_PHONE_NUMBER=${MY_PHONE_NUMBER}
      - API_KEY=${API_KEY}
      - RECORDINGS_PATH=/app/recordings
      - MAX_RECORDING_DURATION=${MAX_RECORDING_DURATION}
    env_file:
      - .env.prod
    volumes:
      - memoora_recordings:/app/recordings
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5005/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  memoora_recordings:
    driver: local 