version: '3.8'

services:
  memoora:
    build: .
    ports:
      - "5005:5005"
    environment:
      - NODE_ENV=development
      - PORT=5005
      - BASE_URL=http://localhost:5005
      - CORS_ORIGIN=http://localhost:3000
    env_file:
      - .env
    volumes:
      - ./recordings:/app/recordings
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5005/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 