version: '3.8'

services:
  memoora-calls:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: memoora-calls-prod
    restart: unless-stopped
    ports:
      - "5005:5005"
    environment:
      - NODE_ENV=production
      - PORT=5005
      - BASE_URL=${BASE_URL}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - ALLOWED_DOMAINS=${ALLOWED_DOMAINS}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - recordings:/app/recordings
      - logs:/app/logs
    networks:
      - memoora-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5005/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: memoora-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - memoora-calls
    networks:
      - memoora-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  recordings:
    driver: local
  logs:
    driver: local

networks:
  memoora-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
