services:
  - type: web
    name: memoora-calls
    env: node
    plan: starter
    buildCommand: npm ci --only=production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5005
      - key: BASE_URL
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: MY_PHONE_NUMBER
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: API_KEY
        sync: false
      - key: API_KEYS
        sync: false
      - key: BLOCKED_NUMBERS
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: APP_BACKEND_URL
        sync: false
      - key: MEMOORA_CALL_SERVICE_API_KEY
        sync: false
      - key: MICROSERVICE_DB_WRITES_ENABLED
        value: true
      - key: TTS_PROVIDER
        value: openai
      - key: ENABLE_QUESTION_READING
        value: true
      - key: VOICE_PERSONALITY
        value: warm-elder
      - key: VOICE_SPEED
        value: 0.85
      - key: VOICE_MODEL
        value: tts-1-hd
      - key: ALLOWED_DOMAINS
        value: memoora.com,frontend-one-ebon-91.vercel.app
      - key: BLOCKED_DOMAINS
        value: spam-domain.com,malicious-site.com
      - key: ALLOWED_COUNTRY_CODES
        value: 1,44,33,49,81
      - key: RECORDINGS_PATH
        value: /tmp/recordings
      - key: MAX_RECORDING_DURATION
        value: 120
      - key: MAX_CALLS_PER_HOUR
        value: 10
      - key: MAX_REQUESTS_PER_HOUR
        value: 100
    healthCheckPath: /health
    autoDeploy: true 